language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

# environment for testing
env:
  - PRIVATE_KEY=pr_test_FjW0q2HMs40Jj3KGua5294sp

# command to run tests
script:
  - black --check setup.py securionpay/ tests/
  - nosetests
