name: Build and validate
on: [ push ]

jobs:
  tests:
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.9 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip -r requirements.txt -r test_requirements.txt

      - name: Run tests
        run: pytest tests

  style-check:
    name: Style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: python -m pip install --upgrade pip -r requirements.txt -r test_requirements.txt

      - name: Run style checks
        run: black --check setup.py securionpay/ tests/